app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /

front:
    resource: "@AppBundle/Resources/config/Front/routing.yml"
    prefix:   /

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
